config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :users
    root to: 'users#index'
  end

  resources :events do
    resources :attendances, except: [:new]
    resources :event_pictures, only: [:create]
  end

  # Defines the root path route ("/")
  root to: "events#index"

  resources :users, only: [:show, :edit, :update]

  # set root redirect '/' to '/gossips' as index 
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :user_join_event_email

  belongs_to :user
  belongs_to :event

  def user_join_event_email
    AttendanceMailer.join_event_email(self).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord

  has_one_attached :event_picture
  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :admin, class_name: 'User'

  validates :start_date, presence: true
  validate :not_passed

  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :valid_duration

  validates :title, presence: true, length: { minimum: 5, maximum: 140 }
  validates :description, presence: true, length: { minimum: 20, maximum: 1000 }
  validates :price, presence: true, length: { minimum: 1, maximum: 1000 }
  validates :location, presence: true

  def not_passed
    if start_date.present? && start_date < Time.now
      errors.add(:start_date, "La date indiquée est dépassée.")
    end
  end

  def valid_duration
    if duration.present? && duration % 5 != 0
      errors.add(:duration, "La duée doit être un mulptiple de 5")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :attendances
  has_many :events, through: :attendances

  has_many :admins, foreign_key:'admin_id', class_name: 'Event'

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_if_admin

  def index
    @users = User.all
    @events = Event.all
  end

  def destroy
    @user = User.find(params[:id])
    Event.all.each do |e|
      if e.admin_id == @user.id
        e.delete
      end
    end
    @user.delete
    flash[:success] = "Utilisateur supprimé"
    redirect_to root_path
  end

  private

  def check_if_admin
    unless current_user&.is_admin
      redirect_to root_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def new
    @attend = Attendance.new
    @event = Event.find(params[:event_id])
    @registered = false
    @check = @event.attendances.all.find_by(user_id: current_user.id)
    if @check
      @registered = true
    end
  end

  def create
    @event = Event.find(params[:event_id])
    @count = @event.users.all.count
    Attendance.create(user_id: current_user.id, event_id: params[:event_id])
  end

end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

  def new
    @attendance = Attendance.new
  end

  def create
    @total = params[:total].to_d
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'eur',
            unit_amount: (@total*100).to_i,
            product_data: {
              name: 'Rails Stripe Checkout',
            },
          },
          quantity: 1
        },
      ],
      mode: 'payment',
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    redirect_to @session.url, allow_other_host: true
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
  end

  def cancel
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
  end
end

app/controllers/event_pictures_controller.rb
class EventsController < ApplicationController

  def create
    @event = Event.find(params[:event_id])
    @event.event_picture.attach(params[:event_picture])
    redirect_to @event
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @registered = false
    @event = Event.find(params[:id])
    @count = Event.find(params[:id]).users.all.count
    if @count > 0 && @event.attendances.find_by(user_id: current_user)
      @registered = true
    else
      @registered = false
    end
  end

  def new
    @event = Event.new
  end

  def create
    if current_user
      @event = Event.new(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location])
      @event.admin_id = current_user.id
      @event.event_picture = params[:event_picture]
      if @event.save
        redirect_to root_path
        flash[:success]= "Ton évenement a bien été créé !"
      else
        render new_event_path
      end
    else
      flash[:alert] = "Vous devez être connecté pour créer un potin"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :check_user

  def show
    @user = User.find(params[:id])
    @events = Event.all
  end

  def check_user
    @user = User.find(params['id'])
    if current_user.id != @user.id && current_user&.is_admin != true
      flash[:danger]= "Bien essayé petit malin ! ;P"
      redirect_to root_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(first_name: params['first_name'], last_name: params['last_name'], description: params['description'])
      flash[:success] = "Votre profil a bien été modifié !"
      redirect_to @user
    else
      render :edit
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/views/admin/users/index.html.erb
<center>
  <br>
  <div>
    <div class="card border-secondary mb-3 admin-size">
      <h2 class="card-txt">Administration</h2>
    </div>
  </div>
  <br><br>

  <div class="card border-secondary mb-3 admin-size">
    <h2 class="card-txt">Utilisateurs</h2>
    <table class="align-tab">
      <div>
        <thead>
          <tr>
            <div>
              <th>ID </th>
              <th>Email</th>
              <th>Prénom</th>
              <th>Nom</th>
            </div>
            <th class="px-2" style="text-align: right;">Action</th>
          </tr>
        </thead>
      </div>
      <tbody>
        <div>
          <% @users.sort.each do |u| %>
            <tr>
              <% if u&.is_admin != true %>
                <td><%= u.id %></td>
                <td><%= u.email %></td>
                <td><%= u&.first_name %> </td>
                <td><%= u&.last_name %></td>
                <td class="session-nav" style="text-align: right;">
                  <%= link_to "Profil", user_path(u.id), :class=>"btn btn-dark gradient-button mx-2" %> 
                  <%= button_to admin_user_path(u.id), form: { data: { turbo_confirm: "Es-tu sur de vouloir supprimer cet utilisateur ?" } }, method: :delete, :class=>"btn btn-dark admin-gradient-button" do %>
                    <%= image_tag("poubelle.png", alt: "delete user", :style=>"height: 18px;") %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </div>
      </tbody>
    </table>
  </div>

</center>

app/views/attendances/new.html.erb
<center>
  <br>
  <% if current_user != @event.admin && @registered == false %>
    <div class="card-center">
      <div class="card" style="width: 550px">
        <div class="card-header">
          <h2 class=" card-txt">Valider votre inscription a l'événement</h2>
        </div>
        <div class="card-body ">
          <%= form_tag('/events', method: 'post' ) do %>
            <div class="mb-3">
              <%= text_field_tag :title, nil, placeholder: "", :class=>"form-control", size: 40 %>
              <br>
              <%= text_area_tag :description, nil, placeholder: "Informations que vous voulez nous communiquer", :class=>"form-control", rows: 4, cols: 42 %>
            </div>
          <% end %>
          <%= button_to "Passer au paiement de #{@event.price}€", checkout_create_path(total: @event.price), class: "btn btn-dark gradient-button m-3", data: {turbo: false} %>
        </div>
      </div>
    </div>
  <% end %>
</center>

app/views/checkout/cancel.html.erb
<div class="container text-center my-5 white-txt">
  <h1>Echec</h1>
  <p>Le paiement n'a pas abouti.</p>
</div>

app/views/checkout/success.html.erb
<div class="container text-center my-5 white-txt">
  <h1>Succès</h1>
  <p>Nous avons bien reçu votre paiement de <%= number_to_currency(@payment_intent.amount_received / 100.0, unit: "€", separator: ",", delimiter: "", format: "%n %u") %>.</p>
  <p>Le statut de votre paiement est : <%= @payment_intent.status %>.</p>
</div>

app/views/events/index.html.erb
<center>
  <div class="container">
    <div class="row">
      <% @events.reverse_each.with_index do |ev| %>
        <div class="col-md-3" style="margin-top: 6%; margin-bottom: 6%" >
          <div class="card-sl">
            <div class="card-heading card-txt">
              <%= ev.title %>
            </div>
            <% if ev.event_picture.attached? %>
              <%= image_tag ev&.event_picture, :class=>"pic-opt" %>
            <% end %>
            <div class="card-text card-txt">
              par <%= link_to "#{ev.admin.first_name}", user_path(ev.admin.id) %>
            </div>
            <div class="card-text card-txt">
              <%= ev.description %>
            </div>
            <div class="card-text card-txt">
              <h6><%= ev.price %>€</h6>
            </div>
            <%= link_to "Voir l'event", event_path(ev.id), :class=>"btn btn-dark gradient-button" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</center>

app/views/events/new.html.erb
<center>
  <br>
  <div class="card-center">
    <div class="card" style="width: 550px">
      <div class="card-header">
        <h2 class=" card-txt">Créer un événement</h2>
      </div>
      <div class="card-body ">
        <%= form_tag('/events', method: 'post', multipart: true) do %>
          <%# <span class="btn btn-dark gradient-button "> %>
            <%# Ajouter une photo pour l'event %>
            <%= file_field_tag :event_picture %>
          <%# </span> %>
          <br><br>
          <div class="mb-3">
            <%= text_field_tag :title, nil, placeholder: "Nom de l'event", :class=>"form-control", size: 40 %>
            <br>
            <%= text_field_tag :location, nil, placeholder: "Lieu de l'event", :class=>"form-control", size: 40 %>
            <br>
            <div class="form-group">
              <%= datetime_field_tag :start_date, nil, class: 'form-control' %>
            </div>
            <br>
            <%= text_field_tag :duration, nil, placeholder: "Durée de l'event", :class=>"form-control", size: 40 %>
            <br>
            <%= text_area_tag :description, nil, placeholder: "Description de l'event", :class=>"form-control", rows: 4, cols: 42 %>
            <br>
            <%= text_field_tag :price, nil, placeholder: "Prix de participation unitaire", :class=>"form-control", size: 40 %>
          </div>
          <%= submit_tag "Mettre en ligne", class: "btn btn-dark gradient-button" %>
        <% end %>
      </div>
    </div>
  </div>
</center>

app/views/events/show.html.erb
<center>
  <br>
  <div>
    <div class="card border-secondary mb-3" style="width: 600px;">
      <h2 class="card-txt"><%= @event.title %></h2>
      <p class="card-header">organisé à <%= @event.location %></p>
      <br>
      <% if @event.event_picture.attached? %>
        <%= image_tag @event.event_picture %>
      <% end %>
      <p class="card-title text-secondary">Description</p>
      <h5 class="card-txt"><%= @event.description %></h5>
      <p class="card-title text-secondary">Dates</p>
      <h5 class="card-txt">Du <%= @event.start_date %> au <%= @event.start_date += @event.duration %></h5>
      <p class="card-txt card-title text-secondary">Pour plus de renseignement, contactez <%= @event.admin.first_name %> par mail : <%= @event.admin.email %></p>
      <p class="card-txt card-title text-secondary"><%= @count %> utilisateur(s) inscrit actuellement</p>
      <h2 class="card-txt">Prix de la participation : <%= @event.price %>€</h2>
      <% if current_user && current_user != @event.admin && @registered == false %>
        <%= button_to "Rejoindre l'événement", event_attendance_path(@event.id), method: 'get', class: "btn btn-dark gradient-button m-3" %>
      <% end %>
    </div>
  </div>
  <br><br>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbrideThp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://js.stripe.com/v3/"></script>
    <script src="https://kit.fontawesome.com/7bec0c7944.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

  </head>

  <body class="back-bg">
    <!-- NAVBAR -->
    <div class="static-nav">
      <nav class="navbar navbar-expand-sm navbar-dark bg-transparent  fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand name-marge">Eventbride</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav navbar-nav-links">
              <!-- Home -->
              <li class="nav-item">
                <%= link_to "Accueil", root_path, :class=>"nav-link" %>
              </li>
              <!-- New event !!!!!!!!!!!! -->
              <% if current_user %>
                <li class="nav-item">
                  <%= link_to "Créer un événement", new_event_path, :class=>"nav-link" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Créer un événement", new_user_session_path, :class=>"nav-link" %>
                </li>
              <% end %>
              <!-- push a droite -->
              <div class="session-nav drop-marge">
                <!-- !! connected !! -->
                <% if current_user %>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dashboard
                    </a>
                    <ul class="dropdown-menu">
                      <% if current_user&.is_admin %>
                        <%= link_to "Administration", admin_root_path, :class=>"dropdown-item" %>
                      <% end %>
                      <%= link_to "Mon profil", user_path(current_user.id), :class=>"dropdown-item" %>
                      <%= link_to "Me deconnecter", destroy_user_session_path, method: :delete, :class=>"dropdown-item", data: {turbo_method: :delete} %>
                    </ul>
                  </li>
                <!-- !! visitor !! -->
                <% else %>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Se connecter
                    </a>
                    <ul class="dropdown-menu">
                      <%= link_to "Se connecter", new_user_session_path, :class=>"dropdown-item" %>
                      <%= link_to "S'incrire", new_user_registration_path, :class=>"dropdown-item" %>
                    </ul>
                  </li>
                <% end %>
              </div>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <br><br><br>
      <% if flash[:success].present? %>
        <div class="alert alert-success custom_alert" role="alert">
          <%= flash[:success] %>
        </div>
      <% end %>
      <% if flash[:alert].present? %>
        <div class="alert alert-danger custom_alert" role="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>
    <!-- NAVBAR END -->
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<center>

    <br>
  <div class="card-center">
    <div class="card" style="width: 550px">
      <div class="card-header">
        <h2 class=" card-txt">Editer votre profil</h2>
      </div>
      <div class="card-body ">
        <%= form_for @user do %>
          <div class="mb-3">
            <%= text_field_tag :first_name, nil, placeholder: "Prénom", :class=>"form-control", size: 40 %>
            <br>
            <%= text_field_tag :last_name, nil, placeholder: "Nom", :class=>"form-control", size: 40 %>
            <br>
            <%= text_area_tag :description, nil, placeholder: "Description", :class=>"form-control", rows: 4, cols: 42 %>
          </div>
          <%= submit_tag "Mettre en ligne", method: :update, class: "btn btn-dark gradient-button" %>
        <% end %>
      </div>
    </div>
  </div>

</center>

app/views/users/show.html.erb
<center>
  <br><br>
  <div class="card-center">
    <div class="card border-secondary mb-3" style="width: 600px;">
      <h2 class="card-txt"><%= @user.first_name %> <%= @user.last_name %></h2>
      <p class="card-header"><%= @user.email %></p>
      <p><%= @user.description %></p>
      <!-- edit des infos user -->
      <%= link_to "Editer le profil", edit_user_path(@user.id), class: "btn btn-dark gradient-button m-3" %>
    </div>
  </div>
  <!-- les gossips de l'user -->
  <div class="container">
    <div class="row">
      <% @events.sort.each do |ev| %>
        <% if ev.admin_id == @user.id %>
          <div class="col-md-3" style="margin-top: 6%; margin-bottom: 6%" >
            <div class="card-sl">
              <div class="card-heading card-txt">
                <%= ev.title %>
              </div>
              <div class="card-text card-txt">
                par <%= link_to "#{ev.admin.first_name}", user_path(ev.admin.id) %>
              </div>
              <div class="card-text card-txt">
                <%= ev.description %>
              </div>
              <div class="card-text card-txt">
                <h6><%= ev.price %>€</h6>
              </div>
              <%= link_to "Voir l'event", event_path(ev.id), :class=>"btn btn-dark gradient-button" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div> 
  </div>
</center>